// src/data.js
export const posts = [
  {
    name: "Nila Akter",
    post: "জয়ে বিশ্বকাপ অভিযান শুরু দক্ষিণ আফ্রিকার",
    author: "Nila",
    caption: "আজকের দিনটি অসাধারণ ছিল!",
    date: "June 3, 2024",
    time: "10:00 AM",
    device: "iPhone",
  },
  {
    name: "Ayesha Khan",
    post: "বাংলাদেশে নতুন প্রযুক্তি উদ্যোক্তা মেলা শুরু হয়েছে।",
    author: "Ayesha92",
    caption: "নতুন উদ্ভাবনের জন্য উত্তেজিত!",
    date: "June 3, 2024",
    time: "11:30 AM",
    device: "Android",
  },
  {
    name: "Mahiya Rani ",
    post: "রাজধানীতে আজ বৃহত্তম বইমেলা অনুষ্ঠিত হচ্ছে।",
    author: "mahi",
    caption: "বইমেলার জন্য অপেক্ষা করতে পারছি না!",
    date: "June 2, 2024",
    time: "5:00 PM",
    device: "Web",
  },
  {
    name: "Kamal Khan",
    post: "সদ্য প্রকাশিত বই 'নন্দিত নরকে' পাঠকদের মন কেড়েছে।",
    author: "khan210",
    caption: "পড়া আসলেই মজার!",
    date: "June 1, 2024",
    time: "8:00 PM",
    device: "Tablet",
  },

  {
    name: "Nila Akter",
    post: "বাংলাদেশ ক্রিকেট দল আজ নিউজিল্যান্ডকে হারিয়েছে!",
    author: "Nila",
    caption: "আজকের দিনটি অসাধারণ ছিল!",
    date: "June 3, 2024",
    time: "10:00 AM",
    device: "iPhone",
  },
  {
    name: "Ayesha Khan",
    post: "বাংলাদেশে নতুন প্রযুক্তি উদ্যোক্তা মেলা শুরু হয়েছে।",
    author: "Ayesha92",
    caption: "নতুন উদ্ভাবনের জন্য উত্তেজিত!",
    date: "June 3, 2024",
    time: "11:30 AM",
    device: "Android",
  },
  {
    name: "Mahiya Rani ",
    post: "রাজধানীতে আজ বৃহত্তম বইমেলা অনুষ্ঠিত হচ্ছে।",
    author: "mahi",
    caption: "বইমেলার জন্য অপেক্ষা করতে পারছি না!",
    date: "June 2, 2024",
    time: "5:00 PM",
    device: "Web",
  },
  {
    name: "Kamal Khan",
    post: "সদ্য প্রকাশিত বই 'নন্দিত নরকে' পাঠকদের মন কেড়েছে।",
    author: "khan210",
    caption: "পড়া আসলেই মজার!",
    date: "June 1, 2024",
    time: "8:00 PM",
    device: "Tablet",
  },
];
